### ISSUE TITLE
Release a version that meets minimum-stability

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#10]
Today, if I try to install the composer package using `composer require`, I get the following error message:

    [InvalidArgumentException]                                                                                                                   
    Could not find package gedcomx-php at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability 

The most current version is `dev-master`. Let's get some semantic versioning on this project.

**Comment by stoicflame** [comment]
+1

**Comment by Dezynworks** [comment]
@stoicflame Where do you want to start versioning? 0.1? 1.0?

**Comment by stoicflame** [comment]
Let's start with 1.0.0.

**Comment by jimmyz** [comment]
Agreed. 1.0.0

**Comment by jimmyz** [comment]
We may want to fix #11 before releasing 1.0.0

**Comment by jimmyz** [comment]
I'm going to create the 1.0.0 tag right now. Build says it's failing, but something must have changed in the Memories API or data that broke a couple of tests. It's not related to the change I made for #11.

**Comment by jimmyz** [comment]
1.0.0 tag now created. Closing.
