### ISSUE TITLE
No way to set an access token on a State object

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#11]
The only class that implements the `authenticateWithAccessToken` function is `Gedcomx\Rs\Client\GedcomxApplicationState`, which has the function protected. As I compare this with the Java project, all of the classes that extend the GedcomxApplicationState implement the `authenticateWithAccessToken` token as a public function.

Is there a reason to not make this public on the `GedcomxApplicationState` class itself?

Without fixing this, there is no way to use this library without using the username/password or clientCredentials OAuth2 flow.

**Comment by shanewalters** [comment]
When this was ported, either this was an oversight by @Dezynworks, or it had already been ported and he didn't change the modifier. It's probably okay to change.

**Comment by stoicflame** [comment]
+1. Let's make it public.
