### ISSUE TITLE
Newer PHP version support

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#12]
Today, the gedcomx-php library supports PHP 5.3. This restricts us from using an older version of Guzzle (guzzle3). I'd like to bump PHP version support to >=5.4.

The primary customer who requested 5.3 is now running 5.5. Are there any objections to bumping the version support and upgrading to a newer Guzzle client?

**Comment by Dezynworks** [comment]
I think the biggest question is how backward compatible Guzzle 4.x is with Guzzle 3.x. I think they're doing semver so that would mean there are breaking changes we'd probably have to address before being able to support >=5.4. Otherwise, I think the rest of the code should run fine.

**Comment by justincy** [comment]
If we switched to version 5 or 6 of guzzle then we could offer [async requests](http://docs.guzzlephp.org/en/latest/quickstart.html#async-requests) in addition to synchronous requests like the AWS SDK does.
