### ISSUE TITLE
Cannot Read Ancestry Resource with Parameter Options

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#13]
The link to the ancestry resource only provides default options. I want to specify generations, personDetails, descendants, and marriageDetails.

```
"ancestry":{
  "href": "https://sandbox.familysearch.org/platform/tree/ancestry?person=KW4V-6T7"
}
```

I don't believe there is a way to do this with the current collection links and with the state transitions.

**Comment by justincy** [comment]
Migrated to https://github.com/FamilySearch/gedcomx-php-client/issues/3
