### ISSUE TITLE
Auto-publish ApiGen Documentation

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#18]
It would be great to have the documentation automatically update when updates are pushed.

A github.io site is now available for this project (found on the gh-pages branch), which hosts the ApiGen docs, which for now have been generated manually. You can see the docs here:

http://familysearch.github.io/gedcomx-php/docs/index.html

Here's instructions on setting up the automatic doc updates with Travis.

https://github.com/ApiGen/ApiGen/wiki/Generate-API-to-Github-pages-via-Travis

**Comment by jimmyz** [comment]
Docs should published in a versioned manner, like this: http://familysearch.github.io/gedcomx-php/docs/1.1/index.html

**Comment by justincy** [comment]
See #41 for information on how generate the docs.

**Comment by justincy** [comment]
ApiGen does not support PHP 5.3. In the future it won't support 5.4. This will break the builds if we try to install if via composer (which is the easier method). Perhaps we'll have to manually install it.

**Comment by justincy** [comment]
I just noticed the guide for publishing via Travis includes steps for installing manually. Nice.

**Comment by justincy** [comment]
We are now automatically updating the docs when the build succeeds on master.
