### ISSUE TITLE
Add the ability to add an User Agent to requests

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#19]
The RS clients should allow you to configure an agent string. This should work according to the HTTP 1.1 spec: http://tools.ietf.org/html/rfc7231#section-5.5.3

If nothing is set, it should set an agent string like this:

`gedcomx-php/1.0.1 Guzzle/3.0.7 curl/7.19.7 PHP/5.5.21`

The application should set the agent:

`AppName/0.0.0 gedcomx-php/1.0.1 Guzzle/3.0.7 curl/7.19.7 PHP/5.5.21`

Thoughts?

**Comment by justincy** [comment]
Any thoughts on a programmatic method for keeping the gedcomx-php version number synced properly?

**Comment by jimmyz** [comment]
Perhaps we need a version file of some sort that gets loaded in the config and then there could be a script task set to bump the version (set the version file, commit it and tag the release).
