### ISSUE TITLE
Throw Exceptions for certain HTTP responses

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#20]
The client should throw exceptions on the following HTTP responses:

* 401 - Unauthorized
* 403 - Forbidden
* 404 - Not found
* 405 - Method not allowed
* 406 - Not Acceptable
* 409 - Conflict
* 410 - Gone
* 415 - Unsupported Media Type
* 429 - Throttled
* 500 - Internal Server Error
* 502 - Bad Gateway
* 503 - Service Unavailable
* 504 - Gateway Timeout

The exceptions should fall within the Gedcomx\Rs\Client\Exception namespace. The exceptions should contain the HTTP response, the code, and the server message.

**Comment by justincy** [comment]
I approve.

**Comment by justincy** [comment]
We're going to implement this as an option in the FamilySearch client, if possible.
