### ISSUE TITLE
Not clear that this library can be used as the SDK for the FamilySearch API

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-php#30]
This repository is billed as "PHP Libraries for GEDCOM X Processing." The readme mentions "Accessing a GEDCOM X RS API." You have to be very familiar with GEDCOM X to know that those statements mean "This library can also be used to access the FamilySearch API."

We should explain this more clearly in the readme. It will be much easier when #24 is complete because we'll be able to show simple sample code.

**Comment by jimmyz** [comment]
Updated README clarifies this.
