### ISSUE TITLE
Make Tests Reliable

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#36]
Every time the tests run, a new random failure appears. There is something strange going on between the tests and the Sandbox API that is causing tests to fail or error out. I believe the testing strategy needs to be reworked to focus on Unit tests. Later, functional tests may be re-introduced, but the current situation makes it nearly impossible to get a build to pass.

**Comment by justincy** [comment]
I just fixed php-vcr. Does that change things?

**Comment by jimmyz** [comment]
Tests are passing reliably now.
