### ISSUE TITLE
Add getPerson() method to PersonsState

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-php#43]
I don't know if the method should accept a plain personId or a [ResourceReference](http://familysearch.github.io/gedcomx-php/docs/class-Gedcomx.Common.ResourceReference.html). Perhaps both.

**Comment by jimmyz** [comment]
I'm thinking ResourceReference, since I believe the use case for this would likely be fetching the person object from the Gedcomx object based upon a reference found within a relationship object.

**Comment by justincy** [comment]
This method could be useful in a lot of other states to (basically any state with a response that could have more than one person in it). So I propose adding `getPerson` to [`Gedcomx\Rs\Client\GedcomxApplicationState`.](http://familysearch.github.io/gedcomx-php/docs/class-Gedcomx.Rs.Client.GedcomxApplicationState.html).

**Comment by justincy** [comment]
Or we could add it to [`PersonsState`](http://familysearch.github.io/gedcomx-php/docs/class-Gedcomx.Rs.Client.PersonsState.html) and have any state extend it that might have multiple persons returned.

**Comment by jimmyz** [comment]
I like that.

**Comment by justincy** [comment]
Turns out it's not that simple. The [PersonsState](http://familysearch.github.io/gedcomx-php/docs/class-Gedcomx.Rs.Client.PersonsState.html) is for the [Persons Resource](https://familysearch.org/developers/docs/api/tree/Persons_resource) which only exists to create persons. The state has an `addPerson` method which wouldn't make sense for any other state. 

Granted, there are some things about it that don't line up. Currently the [PersonsState](http://familysearch.github.io/gedcomx-php/docs/class-Gedcomx.Rs.Client.PersonsState.html) can be obtained in two ways:

1. Calling [`readPersons`](http://familysearch.github.io/gedcomx-php/docs/class-Gedcomx.Rs.Client.CollectionState.html#_readPersons) on [`CollectionState`](http://familysearch.github.io/gedcomx-php/docs/class-Gedcomx.Rs.Client.CollectionState.html). But that call is worthless; it's guaranteed to return a 405 because you can only `POST` to the resource; you can't `GET`.

2. Calling `readPersons` or `readPersonas` on [`SourceDescriptionState`](http://familysearch.github.io/gedcomx-php/docs/class-Gedcomx.Rs.Client.SourceDescriptionState.html). This case makes sense, and it's be used exactly how we would want to use for a list of persons.

Another thing about the PersonsState that doesn't make sense is the `readCollection` method. It appears to be useless. The code performs a `GET` on the `COLLECTION` rel for the given state, but as it stands it's only being used for lists of people which is not a resource and does not have any links (the people have links, but not the lists of people).

I think I'm going to proceed but there's a slight risk that we mess something up because it's in an awkward state to begin with.
