### ISSUE TITLE
Logger usage documentation

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#49]
This project needs usage documentation for assigning a logger to the FamilySearchClient.

**Comment by justincy** [comment]
There is documentation both for the `setLogger()` method and for passing the logger in as a option in to the constructor. Do you want anything else?

**Comment by jimmyz** [comment]
I think there should be an example in some sample code somewhere, probably the wiki. Perhaps it should be added to the sample app to log to STDOUT.

**Comment by justincy** [comment]
Migrated to https://github.com/FamilySearch/gedcomx-php-client/issues/6
