### ISSUE TITLE
Support throttling

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-php#51]
The SDK should recognize and properly handle 429 responses. The responses include headers which tell how long to wait until the next request. That's pretty easy to handle.

**Comment by justincy** [comment]
If `httpExceptions` is set to true (throw exceptions on 400 or 500 level responses) then throttling will be an exception to that behavior. The SDK will catch the error and retry a number of times and then throw a custom exception that means "We tried x many times but never received a successful response".

**Comment by justincy** [comment]
I don't know how to test this behavior. php-vcr needs a way to differentiate requests in order to return different responses, but all requests here will be identical.

**Comment by jimmyz** [comment]
I think throttle handling by the SDK should be configurable.

For testing for throttled responses, the Throttling Guide has been updated with a mechanism to trigger throttled responses. https://familysearch.org/developers/docs/guides/throttling

**Comment by justincy** [comment]
@jimmyz Thanks, that helps a lot.

**Comment by justincy** [comment]
Let's implement this as middleware patterned after the [RedirectMiddleware](https://github.com/guzzle/guzzle/blob/master/src/RedirectMiddleware.php). The behavior is very similar: intercept responses and sometimes issue a new request.

**Comment by ghalpert** [comment]
Is the "Retry-After" header value in milliseconds or seconds? The RFC says seconds, but the Throttling Guide at https://familysearch.org/developers/docs/guides/throttling says milliseconds.

**Comment by justincy** [comment]
@ghalpert It's in seconds. The throttling guide is wrong. I've verified it in the response headers. I've also reported the issue.

**Comment by justincy** [comment]
@jimmyz Do some keys have a special exception to bypass throttling? I can't seem to trigger throttling with a session created during the tests.

**Comment by jimmyz** [comment]
There is a whitelist of keys that bypass throttling. I'll have to check your key with Ryan.

--
Jimmy

From: Justin
Reply-To: FamilySearch/gedcomx-php
Date: Friday, October 16, 2015 at 10:23 AM
To: FamilySearch/gedcomx-php
Cc: Jimmy Zimmerman
Subject: Re: [gedcomx-php] Support throttling (#51)


@jimmyz<https://github.com/jimmyz> Do some keys have a special exception to bypass throttling? I can't seem to trigger throttling with a session created during the tests.

**Comment by justincy** [comment]
Enable throttling in `FamilySearchClient` by setting the `throttling` option to `true`.
