### ISSUE TITLE
Bad Guzzle Version in Composer.json

### ISSUE THREAD

**Issue by jimmyz** [FamilySearch/gedcomx-php#53]
I get an error when trying to install 2.x versions of the SDK. It complains about the guzzle dependency.

"guzzlehttp/guzzle": "dev-master"

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - gedcomx/gedcomx-php v2.0.1 requires guzzlehttp/guzzle dev-master -> no matching package found.
    - gedcomx/gedcomx-php v2.0.0 requires guzzlehttp/guzzle dev-master -> no matching package found.
    - Installation request for gedcomx/gedcomx-php ^2.0 -> satisfiable by gedcomx/gedcomx-php[v2.0.0, v2.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.
```

**Comment by justincy** [comment]
That's odd. I just installed it successfully yesterday. I'll take a look.

I had to pin it to a branch because I had to fix a bug in guzzle in order for it to work. But the guzzle maintainer was in no hurry to cut a new release.

**Comment by justincy** [comment]
@jimmyz I just pushed [an update](https://github.com/FamilySearch/gedcomx-php/commit/330aac69aca7e62cdf73ff7f5a262aa2a65c8993) to pin guzzle to a release. Does that fix it?

**Comment by jimmyz** [comment]
It should fix it. We just need a version bump on this project to validate the error fix.

**Comment by justincy** [comment]
I published a new release this morning.
