### ISSUE TITLE
stuck on Tutorial PHP config -- autoload.php

### ISSUE THREAD

**Issue by jodybrabec** [FamilySearch/gedcomx-php#58]
http://localhost:5000/tutorial.php -- says:

Warning: require(/vendor/autoload.php): failed to open stream: No such file or directory in C:\xamp\htdocs\getcomx-php\tutorial.php

**Comment by jimmyz** [comment]
Looks like there may be an error in the `require` statement. Try changing the require statement to remove the leading forward slash:

`require 'vendor/autoload.php'; `
