### ISSUE TITLE
Can we remove transient properties?

### ISSUE THREAD

**Issue by justincy** [FamilySearch/gedcomx-php#63]
The functionality is defined by the [HasTransientProperties](https://github.com/FamilySearch/gedcomx-php/blob/52704c6e32b1879ac4e4f895a0d167152e6bf1d7/src/Common/HasTransientProperties.php) and implemented by [ExtensibleData](https://github.com/FamilySearch/gedcomx-php/blob/bad8a53112fe4bb68da9ad842a40b9dd5049cb0d/src/Common/ExtensibleData.php) but I can't find any uses of it. Do we need it? Does anybody know what it's there for?

**Comment by stoicflame** [comment]
In the Java SDK, it's used to pass around properties and values that we don't want serialized.

**Comment by justincy** [comment]
Looks like this was removed during the gedcomx-php-client split. (I don't remember doing that)
