### ISSUE TITLE
FamilySearch Php Lite API not working properly

### ISSUE THREAD

**Issue by deboyisgood** [FamilySearch/gedcomx-php#68]
Am trying the familysearch API developed for PHP. when I authenticate,
everything was successful.

Here is the issues am having. on the success page.

1) when i click on "Is User Authenticated? button", it will display error User not authenticated.
2.)When I click on current user button on the left side, it displays this error
status	401 Unauthorized
code	401
message	Unauthorized
the same issue is applicable with the rest like clicking 
 clicking on "Current Person" etc..

Those it means that php session is not well established
after I have successfully authenticated. 
why am I getting those errors above......
This is  urgent to enable me submit my apps. Thanks

**Comment by justincy** [comment]
Migrated to https://github.com/FamilySearch/fs-php-lite/issues/6

**Comment by deboyisgood** [comment]
I have sent you a link to the php family search API, you can test if from your own end. Informations regarding that has been sent to your email at justincyork at gmail [dot]com
please check that, its urgent.

Thanks
